lzc-sdk-version: "0.1"
name: shinobi
package: iamxiaoe.lzcapp.shinobi
version: 0.0.3
description: "The Next Generation in Open-Source Video Management Software with support for over 6000 IP and USB Cameras"
homepage: "https://github.com/ShinobiCCTV/Shinobi"
author: "shinobi"
application:
  subdomain: shinobi
  routes:
    - /=http://shinobi.iamxiaoe.lzcapp.shinobi.lzcapp:8080
  gpu_accel: true # 是否允许使用硬件加速
  depends_on:
    - shinobi

services:
  shinobi:
    image: registry.lazycat.cloud/shinobisystems/shinobi:0.0.1
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - NODE_VERSION=12.21.0
      - YARN_VERSION=1.22.5
      - DB_USER=majesticflame
      - DB_PASSWORD=
      - DB_HOST=localhost
      - DB_DATABASE=ccio
      - DB_PORT=3306
      - SUBSCRIPTION_ID=sub_XXXXXXXXXXXX
      - PLUGIN_KEYS={}
      - SSL_ENABLED=false
      - SSL_COUNTRY=CA
      - SSL_STATE=BC
      - SSL_LOCATION=Vancouver
      - SSL_ORGANIZATION=Shinobi Systems
      - SSL_ORGANIZATION_UNIT=IT Department
      - SSL_COMMON_NAME=nvr.ninja
      - DB_DISABLE_INCLUDED=false
    command: pm2-docker pm2.yml
    entrypoint: sh /home/Shinobi/Docker/init.sh
    binds:
      # - /lzcapp/run/mnt/home/shinobi:/
      - /lzcapp/var/shinobi/customAutoLoad:/customAutoLoad
      - /lzcapp/var/shinobi/home/Shinobi/plugins:/home/Shinobi/plugins
      - /lzcapp/var/shinobi/home/Shinobi/videos:/home/Shinobi/videos
      - /lzcapp/var/shinobi/var/lib/mysql:/var/lib/mysql
